CREATE TABLE dbo.CUTTCusMas
(
	CUSNO		CHAR( 5 )		NOT NULL,
	BRANCH		CHAR( 3 )		NOT NULL,
	CTERRNO		CHAR( 3 )		NOT NULL,
	CSLSMAN1	CHAR( 3 )		NOT NULL,
	CSLSMAN2	CHAR( 3 )		NOT NULL,
	CITY		VARCHAR( 50 )	NOT NULL,
	CONSTRAINT PK_CUTTCusMas PRIMARY KEY( CUSNO )
)
